language: cpp
dist: bionic

git:
  depth: 3

matrix:
  include:
    - name: Linux with GCC 9
      os: linux
      env: CC=gcc-9 CXX=g++-9
    - name: Linux with GCC 8
      os: linux
      env: CC=gcc-8 CXX=g++-8
    - name: Linux with GCC 7
      os: linux
      env: CC=gcc-7 CXX=g++-7
    - name: Linux with Clang 9
      os: linux
      env: CC=clang-9 CXX=clang++-9
    - name: Linux with Clang 8
      os: linux
      env: CC=clang-8 CXX=clang++-8
    - name: macOS with Xcode11/Clang
      os: osx
      osx_image: xcode11
      env: BREW_WORKAROUND=yes
    - name: macOS with Xcode10.3/Clang
      os: osx
      osx_image: xcode10.3
      env: BREW_WORKAROUND=yes
    - name: macOS with Xcode10.1/Clang
      os: osx
      osx_image: xcode10.1

addons:
  apt:
    #update: true
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
      - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
        key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
      - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main"
        key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    packages:
      - g++-9
      - g++-8
      - g++-7
      - clang-9
      - clang-8
      - libasio-dev
      - qt5-default
      - libqt5opengl5-dev
      - libecasoundc-dev
      #- doxygen
      - ecasound
      - libxml2-dev
      - libfftw3-dev
      - libsndfile1-dev
      - libjack-dev
      - libjack0
      - help2man
      - jackd1
      - pkg-config
      - libtool
  homebrew:
    update: true
    packages:
      - asio
      - autoconf
      #- doxygen
      - ecasound
      - fftw
      - jack
      - liblo
      - libsndfile
      - libxml2
      - qt
      # using brew, it's not possible to install needed perl dependencies for
      # help2man (Locale::gettext), therefore best disabled for now
      #- help2man

before_install:
  # https://github.com/Homebrew/brew/issues/5068#issuecomment-429984836
  - if [ "$BREW_WORKAROUND" = yes ]; then sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target / ; fi

before_script:
  - ci/build-deps.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/qt/lib/pkgconfig:/usr/local/lib/pkgconfig; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/qt/bin:$PATH"; fi
  - ./autogen.sh

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure --prefix='/usr'; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make && sudo make install; fi

after_failure:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ls -alhv /usr/bin/ |grep -E "(clang|gcc|g\+\+)"; fi
  - if [[ -f config.log ]]; then cat config.log; fi

branches:
  only:
    - master
    - networking-with-osc
    - travis-integration

notifications:
  email: false
