# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build_docs:
    docker:
      # https://github.com/dante-ev/docker-texlive
      - image: danteev/texlive

    working_directory: ~/checkout

    environment:
      PIP_INSTALL: python3 -m pip install --user --progress-bar off --upgrade

    steps:
      - checkout

      - run:
          name: Checkout Submodules
          command: |
            git submodule update --init

      - run:
          name: Set $PATH (for Python entry points)
          command: |
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV

      - run:
          name: Installing Python Packages
          command: |
            $PIP_INSTALL sphinx sphinx-rtd-theme

      - run:
          name: Installing apt Packages
          command: |
            apt-get update
            apt-get install -y \
              automake \
              doxygen \
              libfftw3-dev \
              libjack-jackd2-dev \
              libsndfile1-dev \
              libxml2-dev \
              pkg-config \
              yarnpkg

      - run:
          name: Building HTML Manual
          command: |
            cd doc/manual
            make html

      - store_artifacts:
          name: Uploading HTML Manual
          path: doc/manual/_build/html
          destination: manual

      - run:
          name: Building PDF Manual
          command: |
            cd doc/manual
            make latexpdf

      - store_artifacts:
          name: Uploading PDF Manual
          path: doc/manual/_build/latex/SoundScapeRenderer.pdf
          destination: SoundScapeRenderer.pdf

      - run:
          name: Configuring SSR (only browser GUI)
          command: |
            ./autogen.sh
            ./configure \
              --disable-all \
              --disable-ecasound \
              --disable-gui \
              --disable-ip-interface \
              --disable-websocket-interface \
              --enable-browser-gui

      - run:
          name: Building the SSR (only browser GUI files)
          command: |
            make
            make DESTDIR=~/install install

      - store_artifacts:
          name: Uploading Browser GUI files
          path: ~/install/usr/local/share/ssr/websocket_resources
          destination: browser-gui

      - run:
          name: Building Doxygen docs
          command: |
            make doc

      - store_artifacts:
          name: Uploading Doxygen HTML files
          path: doc/doxygen/html
          destination: doxygen

workflows:
  version: 2
  i-would-like-some-docs:
    jobs:
      - build_docs
