name: Build Pd Externals for macOS
on: [push, pull_request]
jobs:
  flext:
    runs-on: macos-latest
    steps:
    - name: install macOS packages
      run: |
        brew install fftw libsndfile cunit pkg-config

    - name: checkout pure-data
      uses: actions/checkout@v2
      with:
        repository:  pure-data/pure-data
        path: pure-data

    - name: checkout flext
      uses: actions/checkout@v2
      with:
        repository:  grrrr/flext
        path: flext

    - name: build and install flext
      working-directory: flext
      run: |
        ./build.sh pd gcc || true
        echo "PDPATH=$GITHUB_WORKSPACE/pure-data" >> buildsys/config-mac-pd-gcc.txt
        ./build.sh pd gcc || true
        ./build.sh pd gcc
        sudo ./build.sh pd gcc install

    - name: checkout ssr
      uses: actions/checkout@v2
      with:
        submodules: true
        path: ssr

    - name: checkout libmysofa
      uses: actions/checkout@v2
      with:
        repository: hoene/libmysofa
        path: libmysofa

    - name: build libmysofa
      working-directory: libmysofa/build
      run: |
        cmake ..
        make
        sudo make install

    - name: build externals
      working-directory: ssr/flext
      run: |
        make FLEXTPATH="$GITHUB_WORKSPACE/flext"

    - name: upload macOS externals
      uses: actions/upload-artifact@v2
      with:
        name: macos-externals
        path: ssr/flext/pd-darwin/release-single/*.pd_darwin
